### PR TITLE
Wrong character code?

### PR DESCRIPTION
**Pull request by WebVeteran**
I believe `&#0;` should be `&#x0;`

### CODE REVIEW

**Comment by thomich** [comment]
if we check https://github.com/christiaan/tinymce-codemirror/blob/master/plugins/codemirror/source.html#L206 then you're right ;)

it must be `&#x0;`

**Comment by christiaan** [comment]
@thomich or @WebVeteran I've made both of you collaborators as you appear to be using the actual code a lot more than I am doing (I quit my job where we were using it). So if the two of you agree on a fix after reviewing it feel free to merge it yourself (as far as I know you should be able to).

Thanks again for contributing back!

**Comment by WebVeteran** [comment]
I just started using this, so I'm not too familiar with the code just yet. But I'll do my best as I am very interested in the project. Hopefully you'll still be around to answer questions.

**Comment by thomich** [comment]
hey @christiaan @WebVeteran and other contributors

i also try my best.. i'm working with tinymce since about 12 or more years.. with codemirror for tinymce i started work this year... we will handle that ;)... but if we still can work all together, would be nice...

thomi

**Pull request merged**
